package ar.com.lucianoclusa.minesweeper.infrastructure.entity;

import ar.com.lucianoclusa.minesweeper.domain.Game;
import ar.com.lucianoclusa.minesweeper.domain.User;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

@DynamoDBTable(tableName = "users")
public class UserEntity {
    private String id;
    private List<String> gameIds;
    private String userName;

    public UserEntity(User user) {
        this.id = user.getUserId();
        this.userName = user.getUserName();
        this.gameIds = user.getUserGameIds();
    }

    public User toUser() {
        return new User(this.id, this.userName, this.gameIds);
    }

    public UserEntity() {}

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public List<String> getGameIds() {
        return gameIds;
    }

    public void setGameIds(List<String> gameIds) {
        this.gameIds = gameIds;
    }

    @DynamoDBAttribute
    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }
}
